version: '3'
services:
  appVendas:
    container_name: vendas
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=dbVendas
    depends_on:
      - dbVendas
    networks:
      - app-network

  dbVendas:
    container_name: dbVendas
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    networks:
      - app-network

networks:
  app-network:
    external: true