version: '3'
services:
  appVeiculos:
    container_name: veiculos
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5434
      - PG_HOST=dbVeiculos
    depends_on:
      - dbVeiculos
    networks:
      - app-network

  dbVeiculos:
    container_name: dbVeiculos
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5434"
    networks:
      - app-network

networks:
  app-network:
    external: true