version: '3'
services:
  appPagamentos:
    container_name: pagamentos
    build:
      context: .
      dockerfile: project/Dockerfile
    ports:
      - "8005:8005"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5433
      - PG_HOST=dbPagamentos
    depends_on:
      - dbPagamentos
    networks:
      - app-network

  dbPagamentos:
    container_name: dbPagamentos
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5433"
    networks:
      - app-network

networks:
  app-network:
    external: true